### ISSUE TITLE
Have you reproduced the result?

### ISSUE THREAD

**Issue by guotong1988** [sebastian-hofstaetter/neural-ranking-drmm#1]
Result in paper.
Thank you!
@sebastian-hofstaetter

**Comment by sebastian-hofstaetter** [comment]
Hi,
No, unfortunately I was not able to reproduce DRMM results for Robust 04 - in my current research on neural IR models using MS MARCO I also observed DRMM is not outperforming BM25 (In contrast other models do outperform BM25 by a large margin on the MS MARCO passage re-ranking task). 
If you want to know more about the better models visit (with re-implementations in PyTorch): https://github.com/sebastian-hofstaetter/sigir19-neural-ir

**Comment by guotong1988** [comment]
Thank you!
