### ISSUE TITLE
pre-ranked file (for test data)

### ISSUE THREAD

**Issue by PSanni** [sebastian-hofstaetter/neural-ranking-drmm#2]
While pre-processing it ask for 

pre-ranked file and it should be from the same test collection. Do you know how i can get this pre-ranked file ??? 

Thanks

**Comment by sebastian-hofstaetter** [comment]
Hi,

You need an initial ranking per query, for example with BM25 - so that the neural model does not need to score all query document pairs. I recommend using Anserini https://github.com/castorini/anserini/
